import type { Metadata } from "next";
import "../globals.css";
import dynamic from "next/dynamic";
import { Toaster } from "@/components/ui/sonner";
const Footer = dynamic(() => import("@/components/layout/footer/Footer"));
const Header = dynamic(() => import("@/components/layout/header/Header"));

export const metadata: Metadata = {
  title: "Truescholar",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen flex flex-col">
      <Header />
      <main className="flex-grow">{children}</main>
      <Toaster />
      <Footer />
    </div>
  );
}
